name = "handypay-backend"
main = "dist/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[build.upload]
format = "modules"

# Environment variables
[vars]
DATABASE_URL = "postgresql://postgres.cmovosoqdskzdojsmndh:huxwAw-wovjuk-honzy1@aws-1-us-east-1.pooler.supabase.com:5432/postgres?pgbouncer=true&connection_limit=1"
BETTER_AUTH_URL = "https://handypay-backend.handypay.workers.dev"
BETTER_AUTH_SECRET = "SEmw3km2t64VbFEOd4BV5zlGQ1HdkAKl"

# OAuth configurations
GOOGLE_CLIENT_ID = "372273128345-josn5129vti7h8o17h0lbeskd0p46c6g.apps.googleusercontent.com"
APPLE_CLIENT_ID = "com.handyhurry.signin"

# Stripe (test keys for now)
STRIPE_TEST_SECRET_KEY = "sk_test_51PuKMgHp4jzbtGa46Vm7sqH19ZPvxGBvSwTnHIXPqvtBRbjfZbxSDSmgWGT9k0qdO30urRCgy1j4rrqKjOb2KmeQ004e47suiV"
STRIPE_TEST_WEBHOOK_SECRET = "whsec_U3PYdi0oAkHIPngr1lOflqAorZ5n2aeH"

# Supabase
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnaGRkb3hlaWx6bXNqbW14ZXRqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0OTMzNTkzNywiZXhwIjoyMDY0OTExOTM3fQ.RAGh7_v41t9kbAi738I_MUPgt8a7xmxC02DyHfDE-zs"
