name = "handypay-backend"
main = "dist/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[build.upload]
format = "modules"

# Environment variables - Set via Cloudflare Workers dashboard or wrangler secrets
# DO NOT commit actual secret values to repository
[vars]
BETTER_AUTH_URL = "https://handypay-backend.handypay.workers.dev"
DATABASE_URL = "postgresql://postgres.cmovosoqdskzdojsmndh:huxwAw-wovjuk-honzy1@aws-1-us-east-1.pooler.supabase.com:5432/postgres?pgbouncer=true&connection_limit=1"

# OAuth configurations (set via wrangler secrets)
# GOOGLE_CLIENT_ID, APPLE_CLIENT_ID, etc. should be set via wrangler secrets
# or Cloudflare Workers environment variables, not committed to repo

# Example of how to set secrets:
# npx wrangler secret put DATABASE_URL
# npx wrangler secret put BETTER_AUTH_SECRET
# npx wrangler secret put GOOGLE_CLIENT_ID
# etc.
